name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # ВАЖЛИВО: мінімум 18, краще 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with vitest
        run: npx vitest run --coverage
